# Generated by Django 2.1.2 on 2021-04-07 19:00

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('language', models.CharField(max_length=40)),
                ('level', models.CharField(default='', max_length=40)),
                ('problem', models.TextField(max_length=1000)),
                ('solution', models.TextField(max_length=1000)),
                ('date', models.DateField(default=datetime.date(2021, 4, 8))),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
