# Generated by Django 2.1.2 on 2021-04-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='username',
            field=models.CharField(default='', max_length=40),
        ),
    ]
